language: ruby
rvm:
  - 2.3
# whitelist branches that run in CI
branches:
  only:
  - master
  - canary

script: true

# deploy changes on master to lich repo
deploy:
  provider: script
  script: util/repo
  on:
    branch: master
