name: Publish gameobj-data
on:
  push:
    branches: [ 'master' ]
    paths:
      - 'lib/**'
      - 'spec/gameobj-data/**'
      - 'type_data/**'
      
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish gameobj-data
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '20'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Setup bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run type data migrations to create gameobj-data.xml
        run: bin/migrate
      - name: Pushes GameObj-data.xml file
        run: |
          rm -rf temp_jinx
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/elanthia-online/jinx.git temp_jinx
          cp dist/gameobj-data.xml temp_jinx/lib/
          git add temp_jinx
          git commit -m "Automatic publish from github.com/elanthia-online/scripts"
          git push temp_jinx master
