name: RSpec Tests
on: 
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7']
    name: Run tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install xmllint
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libxml2-utils
          version: 1.0
      - name: Run type data migrations to create gameobj-data.xml
        run: bin/migrate
      - name: Run RSpec tests
        run: bundle exec rspec
